import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import os
from dotenv import load_dotenv

load_dotenv()

def send_newsletter(content_html, subject="[주간 브리핑] HBM 및 메모리 반도체 동향"):
    """
    구성된 HTML 뉴스레터를 이메일로 발송합니다.
    """
    smtp_server = os.getenv("EMAIL_SMTP_SERVER")
    smtp_port = int(os.getenv("EMAIL_SMTP_PORT", 587))
    smtp_user = os.getenv("EMAIL_USER")
    smtp_password = os.getenv("EMAIL_PASSWORD")
    recipient_emails = os.getenv("RECIPIENT_EMAILS", "").split(",")

    if not all([smtp_server, smtp_user, smtp_password, recipient_emails]):
        print("이메일 설정이 누락되었습니다. (.env 파일을 확인하세요)")
        return False

    try:
        msg = MIMEMultipart()
        msg['From'] = smtp_user
        msg['To'] = ", ".join(recipient_emails)
        msg['Subject'] = subject

        msg.attach(MIMEText(content_html, 'html'))

        with smtplib.SMTP(smtp_server, smtp_port) as server:
            server.starttls()
            server.login(smtp_user, smtp_password)
            server.send_message(msg)
            
        print(f"이메일 발송 성공: {len(recipient_emails)}명에게 전달되었습니다.")
        return True
    except Exception as e:
        print(f"이메일 발송 실패: {e}")
        return False

def format_as_html(news_summary, paper_summary):
    """
    요약된 내용을 이메일용 HTML로 변환합니다.
    이미지 URL이 포함된 경우 <img> 태그를 삽입합니다.
    """
    import re

    def process_summary(text):
        # 1. Image URL 패턴을 더 유연하게 찾기 (4. Image: 또는 그냥 URL)
        processed = []
        # 뉴스 항목들을 분리 (번호로 시작하거나 빈 줄로 구분된 경우 대응)
        items = re.split(r'\n\s*\n|\n(?=\d+\.\s*제목:)', text)
        
        for item in items:
            if not item.strip(): continue
            
            # 이미지 URL 추출 (4. Image: URL 또는 텍스트 내의 URL 추출)
            img_match = re.search(r'4\. Image:\s*(https?://\S+)', item)
            if not img_match:
                # 4번 형식이 아닐 경우를 대비해 텍스트 내의 일반 이미지 URL 검색 (구글 서버 제외)
                img_urls = re.findall(r'https?://\S+\.(?:jpg|jpeg|png|gif|webp)(?:\?\S+)?', item, re.IGNORECASE)
                img_url = next((u for u in img_urls if "googleusercontent.com" not in u and "gstatic.com" not in u), None)
            else:
                img_url = img_match.group(1)
                if "None" in img_url or "googleusercontent.com" in img_url:
                    img_url = None

            item_html = item.replace('\n', '<br>')
            # 형식 태그 제거 (번호 등)
            item_html = re.sub(r'<br>\d+\.\s*Image:.*', '', item_html)
            
            if img_url:
                item_html = f"""
                <div style="margin-bottom: 15px; text-align: center;">
                    <a href="{img_url}" target="_blank">
                        <img src="{img_url}" alt="News Image" style="max-width: 100%; height: auto; max-height: 400px; border-radius: 8px; border: 1px solid #eee; display: inline-block;">
                    </a>
                </div>
                {item_html}
                """
                
            processed.append(f'<div class="item">{item_html}</div>')
        
        return "\n".join(processed)

    news_html = process_summary(news_summary)
    paper_html = process_summary(paper_summary)

    html = f"""
    <html>
    <head>
        <style>
            body {{ font-family: 'Malgun Gothic', sans-serif; line-height: 1.6; color: #333; background-color: #f4f7f6; }}
            .container {{ max-width: 700px; margin: 20px auto; padding: 30px; background: #fff; border-radius: 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }}
            h1 {{ color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 15px; text-align: center; }}
            h2 {{ color: #2980b9; margin-top: 40px; border-left: 5px solid #3498db; padding-left: 15px; }}
            .item {{ margin-bottom: 30px; padding: 20px; background: #ffffff; border: 1px solid #e1e8ed; border-radius: 8px; }}
            .footer {{ margin-top: 50px; font-size: 0.85em; color: #7f8c8d; text-align: center; border-top: 1px solid #eee; padding-top: 20px; }}
            img {{ display: block; margin: 0 auto 15px; }}
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🚀 주간 HBM & 메모리 반도체 동향</h1>
            <p style="text-align: center; color: #7f8c8d;">이 리포트는 AI(Gemini 3 Flash)를 통해 수집 및 분석되었습니다.</p>
            
            <h2>📰 주요 뉴스 (Core News)</h2>
            {news_html}

            <h2>📚 주요 논문 (Research Papers)</h2>
            {paper_html}

            <div class="footer">
                © 2026 Memory Trends Weekly | Generated by Google Gemini Flash<br>
                본 메일은 수신 동의를 하신 분들께 발송되는 정기 기술 브리핑입니다.
            </div>
        </div>
    </body>
    </html>
    """
    return html
